spring:
  profiles:
    active: local
  application:
      name: springDataFlow
  batch:
    jdbc:
      initialize-schema: always

store:
  domain:
    datasource:
      poolName: issue-domain-cp
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: "jdbc:mysql://localhost:3306/store?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul"
      username: root
      password: root
      auto-commit: false
      sqlScriptEncoding: UTF-8
      connectionTimeout: 60000
      maxLifetime: 60000
      maximumPoolSize: 5

backup:
  domain:
    datasource:
      poolName: issue-domain-cp
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: "jdbc:mysql://localhost:3306/backup?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul"
      username: root
      password: root
      auto-commit: false
      sqlScriptEncoding: UTF-8
      connectionTimeout: 60000
      maxLifetime: 60000
      maximumPoolSize: 5


logging:
  level:
    com.example.spring.batch: DEBUG
